//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eticaretEntities : DbContext
    {
        public eticaretEntities()
            : base("name=eticaretEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategori> Kategori { get; set; }
        public virtual DbSet<KULLANICILAR1> KULLANICILAR1 { get; set; }
        public virtual DbSet<Odeme1> Odeme1 { get; set; }
        public virtual DbSet<Sepet1> Sepet1 { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UrunListesi> UrunListesi { get; set; }
        public virtual DbSet<BeniHatirla> BeniHatirla { get; set; }
    }
}
