//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret
{
    using System;
    using System.Collections.Generic;
    
    public partial class KULLANICILAR1
    {
        public int UserID { get; set; }
        public string UserAdi { get; set; }
        public string UserSoyadi { get; set; }
        public string UserMail { get; set; }
        public string UserSifre { get; set; }
        public string Rol { get; set; }
    }
}
