//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odeme1
    {
        public int OdemeID { get; set; }
        public string KullaniciID { get; set; }
        public string OdemeAd { get; set; }
        public string OdemeAdres { get; set; }
        public string OdemeTelNo { get; set; }
    }
}
