//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet1
    {
        public int SepetID { get; set; }
        public string SepetFoto { get; set; }
        public string SepetAdi { get; set; }
        public Nullable<int> SepetFiyat { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
