//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ETicaret
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunListesi
    {
        public int UrunID { get; set; }
        public string kategori { get; set; }
        public string UrunAdi { get; set; }
        public Nullable<int> UrunFiyat { get; set; }
        public string UrunFoto { get; set; }
        public string UrunOzellik { get; set; }
        public string UrunOzellik2 { get; set; }
        public string UrunFoto1 { get; set; }
        public string UrunFoto2 { get; set; }
        public string UrunFoto3 { get; set; }
    }
}
